version: '3.3'

services:
   rtmp:
      build: ./nginx
      restart: always
      ports:
         - "80:80"
         - "1935:1935"
      container_name: rtmp_server

   auth:
      build: ./auth
      restart: always
      container_name: rtmp_auth