version: '3.5'

services:
   rtmp:
      build: ./nginx
      restart: always
      ports:
         - "80:80"
         - "1935:1935"
      container_name: rtmp_server
      depends_on:
         - auth

   auth:
      build: ./auth
      restart: always
      container_name: rtmp_auth