version: '3.7'

services:
   # for autenticating stream keys
   auth:
      build: ./auth
      restart: always
      # backend server, do not map ports to external world
      expose:
         - "5000"
      container_name: auth_server
   
   # for ingesting and converting RTMP to HLS
   nginx:
      build: ./nginx
      restart: always
      depends_on:
         - auth
      ports:
         - "1935:1935" # RTMP stream in
         - "80:80" # HLS stream out
      container_name: rtmp_server